### ISSUE TITLE
httpclient dependencies Load error

### ISSUE THREAD

**Issue by smdern** [lostisland/faraday-httpclient#2]
Commit [0f1d8a2](https://github.com/lostisland/faraday-httpclient/commit/0f1d8a2c7240fd7722a82d7d6afe2fc4f1345b8b#diff-011fe555eaf6bba3c851936056e8042a6364a150b336b34b66ac3d8936c2f03dR3) changed how `httpclient` is loaded, which is causing `LoadErrors` unless we explicitly add `httpclient` as a dependency.

I think `httpclient` should be listed as a runtime dependency in the gemspec, rather than a development dependency.

**Comment by smdern** [comment]
I see you're actively working on it.

**Comment by iMacTia** [comment]
Thanks for raising this @smdern, I'm happy to say this has been fixed in https://github.com/lostisland/faraday-httpclient/commit/c7d0dfb76a90bc9684aaffbb9497a97764ae2f97 and have just been released.
Any feedback welcome 🙌 !

**Comment by smdern** [comment]
v 2.0.1 Looks good. Thank you
